site_name: IOpy documentation
pages:
    - About: index.md
    - Theory: theory.md
    - Library: Library.md
    - Examples: Examples.md
    - Outlook: outlook.md
    - References: references.md
# Enabling LaTeX math equations
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
