site_name: IOpy documentation
pages:
    - About: index.md
    - Theory: theory.md
    - Library: Library.md
    - Examples: Examples.md
    - Outlook: outlook.md
    - References: references.md

# Enabling LaTeX math equations
markdown_extensions: 
    - mdx_math:
        enable_dollar_delimiter: True
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']